% ------ SFRJ Internal Ballistic Simulator / UCF CAPSTONE PROJECT ------ %
% File Name: Gas.m 
% 
% File Description: 
% Gas model, calculates combustion chamber pressure and air mass
% properties
% 
% Name            Date      SCR  Description
% --------------  --------  ---  ------------------------------
% Ethan Sherlock  01/22/21  000  Initial Creation 
% Ethan Sherlock  02/14/21  001  Chamber Pressure Calculation Update
% ---------------------------------------------------------------------- %

% Set Inlet velocity and pressure
InltVel(n) = InltVel(1);
InltPres(n) = InltPres(1);

f(n) = MFuelGen(n) / SFRJDt;        % 

% Chamber pressure (PC) based on Austins reverse nozzle area calculations
PC(n) = (3/(121*(NzlAT^2))) * ((20*sqrt(5))*sqrt(121*(NzlAT^2)*(InltArea^2)*InltRho(1)*InltPres(n)...
      - 33*NzlAT*f(n)*(InltArea^2)*InltRho(1) + 4500*(InltArea^4)*InltRho(1)^2) ...
      + 11*NzlAT*f(n) - 3000*(InltArea^2)*InltRho(1));
   
% Required chamber pressure for exit Mach = 2 
[mach, T, P, rho, area] = flowisentropic(gamma_nzlT(n), 2 ,'mach'); % Solves for conditions when exit Mach = 2
PCreq(n) = (1/P)*BackPres(n);                                       % Calculates Stag Pres based on Pressure ratio, assumes Pstag = PC

% Calculate air velocity after sudden expansion inside the chamber 
AirVel(n) = InltVel(n) * (InltArea/PortArea(n));                    % Velocity of air 

% Calculate air mass properties
MairGen(n) = AirVel(n) * InltRho(1) * PortArea(n) * SFRJDt;         % Mass of air generated (kg)
MOxdzrGen(n) = MairGen(n) * 0.2314;                                 % Mass of oxygen generated by weight % (kg)        
MdotAir(n) = MairGen(n)/SFRJDt;                                     % Air mass flow rate (kg/s)
MdotTotal(n) = MdotAir(n) + MdotFuel(n);                            % Total mass flow (kg/s)


% Chamber Pressure based on adiabatic flame temp
[mach, T, P, rho, area] = flowisentropic(1.321, 1 ,'mach');         % Isentropic flow conditions at nozzle throat
T_static(n)	= T*T_stag(n);                                          % Find static temp (K)
V_soundNzlT(n) = sqrt(1.3845*287.05*T_static(n));                   % Speed of sound at nozzle throat (m/s)
V_flowRate(n) = mach * V_soundNzlT(n);                              % Flow velocity at nozzle throat (m/s)
Rho_static(n) = MdotTotal(n)/(V_flowRate(n) * NzlAT);               % Static density at nozzle throat (kg/m^3)
Rho_stag(n) = (1/rho)*Rho_static(n);                                % Stagnation density at nozzle throat (kg/m^3)
PC_TAFT(n) = Rho_stag(n)*287.05*T_stag(n) * (1/Pa2kPa);             % Stagnation pressure = chamber pressure (kPa)
