% ------ SFRJ Internal Ballistic Simulator / UCF CAPSTONE PROJECT ------ %
% File Name: Gas.m 
% 
% File Description: 
% Gas model, calculates combustion chamber pressure and air mass
% properties
% 
% Name            Date      SCR  Description
% --------------  --------  ---  ------------------------------
% Ethan Sherlock  01/22/21  000  Initial Creation 
% Ethan Sherlock  02/14/21  001  Chamber Pressure Calculation Update
% Ethan Sherlock  03/12/21  002  Added Chemistry Model 
% ---------------------------------------------------------------------- %

% Calculate air mass properties
intake.MassGen(n) = intake.massFlow(end,n)*SFRJDt;                                     % Mass of air generated (kg)
intake.OxygenGen(n) = intake.MassGen(n) * constants.OxPercent;                              % Mass of oxygen generated by weight % (kg)        
vehicle.TotalMassFlow(n) = intake.massFlow(end,n) + fuel.MassFlow(n);                            % Total mass flow (kg/s)
combustion.OFRatio(n) = intake.OxygenGen(n)/fuel.MassGen(n);                              % O/F Ratio
vehicle.TotalMassGen(n) = intake.MassGen(n) + fuel.MassGen(n);                              % Total mass generated (kg)
combustion.FAR(n) = (fuel.MassGen(n)/intake.MassGen(n));                              % fuel to air ratio 

% --------------------- Chemistry Model --------------------- %
[combustion.Phi(n), vehicle.AFT(n), nozzle.gamma(n), nozzle.R(n)] = chem.phiSolver(combustion.FAR(n),intake.staticTemp(end,n));     % Call Chemistry Model, need to add T_air before combustion chamber 475


